version: "3"
networks:
  udagram:
    driver: bridge
services:
  reverseproxy:
    image: datacamp042/udagram-reverseproxy
    build:
      context: udagram-reverseproxy
    ports:
      - 8080:8080
    restart: always
    networks:
      - udagram
  backend-user:
    image: datacamp042/udagram-api-user
    build:
      context: udagram-api-user
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB                    
      POSTGRES_HOST: $POSTGRES_HOST                         # or host.docker.internal if you're using a Audi Development Machine
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
    networks:
      - udagram
  backend-feed:
    image: datacamp042/udagram-api-feed
    build:
      context: udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST                         # or host.docker.internal if you're using a Audi Development Machine
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
    networks:
      - udagram
  frontend:
    image: datacamp042/udagram-frontend
    build:
      context: udagram-frontend
    ports:
      - "8100:80"
    networks:
      - udagram